/**
 * Tree-fetch query builder for `issues tree <ID>` (DEV-4480).
 *
 * GraphQL has no native depth-N recursion, so the query is generated by
 * nesting `children { nodes { ... } }` N times at build time. This keeps
 * the *fetch* to a single round-trip even for deep trees, at the cost of
 * a larger query string.
 *
 * Each level fetches the minimal field set needed to render a tree entry:
 * id, identifier, title, state.{name,type}, assignee.name. State.type is
 * present so the renderer can flag terminal states (Done / Canceled) and
 * the caller's `--include-closed` filter can be applied client-side after
 * the fetch (Linear doesn't accept a top-level filter that scopes to the
 * issue subtree — the children connection is filterless).
 *
 * Depth bounds: `1` (just the root + its direct children) through `5`.
 * Above 5 the query string grows too large to be useful as a single call;
 * callers wanting deeper walks should iterate `tree` on leaf nodes.
 */

export const MIN_TREE_DEPTH = 1;
export const MAX_TREE_DEPTH = 5;
export const DEFAULT_TREE_DEPTH = 3;

// Field set per tree node — kept minimal so the depth-N query stays small.
// `state.type` is required client-side for `--no-include-closed` pruning;
// `state.name` for the [Done]/[Canceled] suffix on terminal nodes.
// `completedAt` is the moment a node reached a terminal state (null while
// open) — consumers that reason about how long a subtree has been finished
// (e.g. el-sop health's completed-children grace period, DEV-5454) need the
// per-child timestamp, which no other field carries.
// `priority` was intentionally dropped after cycle-1: the ASCII formatter
// doesn't render it and including it inflates the query string by ~N nodes.
const TREE_NODE_FIELDS = `
	id
	identifier
	title
	state { id name type }
	assignee { id name }
	completedAt
`;

/**
 * Recursive children fragment generator. `depth=0` emits nothing (no
 * children fetched at this level — terminal); `depth=1` emits a single
 * `children { nodes { ...fields } }`; higher depths nest further.
 */
function buildChildrenBlock(depth: number): string {
	if (depth <= 0) {
		return "";
	}
	return `
		children {
			nodes {
				${TREE_NODE_FIELDS}
				${buildChildrenBlock(depth - 1)}
			}
		}
	`;
}

export function buildIssueTreeQuery(depth: number): string {
	if (
		!Number.isInteger(depth) ||
		depth < MIN_TREE_DEPTH ||
		depth > MAX_TREE_DEPTH
	) {
		throw new Error(
			`Tree depth must be an integer in [${MIN_TREE_DEPTH}, ${MAX_TREE_DEPTH}]; got ${depth}`,
		);
	}
	return `
		query GetIssueTree($id: String!) {
			issue(id: $id) {
				${TREE_NODE_FIELDS}
				${buildChildrenBlock(depth)}
			}
		}
	`;
}

/**
 * Shape of a single tree node — used for both the GraphQL response and
 * the post-filter return value (after `--include-closed` is applied
 * client-side).
 */
export interface IssueTreeNode {
	id: string;
	identifier: string;
	title: string;
	state: { id: string; name: string; type: string } | null;
	assignee: { id: string; name: string } | null;
	/** ISO timestamp the node reached a terminal state; null while open. */
	completedAt?: string | null;
	children?: { nodes: IssueTreeNode[] };
}

export interface GetIssueTreeResponse {
	issue: IssueTreeNode | null;
}
