/**
 * `el-linear issues tree <ID>` (DEV-4480).
 *
 * Renders the parent-and-children tree of an issue to depth N (default 3,
 * max 5 — see `MAX_TREE_DEPTH`). One GraphQL round-trip per invocation;
 * the query string is generated by `buildIssueTreeQuery(depth)` at call
 * time because the children connection has no `@include`-style depth
 * directive.
 *
 * Two output modes:
 *   - **JSON** (default): nested `IssueTreeNode` shape.
 *   - **Summary**: ASCII tree via `formatTree`.
 *
 * Closed-issue filtering: `--include-closed` is on by default for `tree`
 * because the tree's value is *structural* — knowing that a child was
 * canceled is part of the picture. Pass `--no-include-closed` to prune
 * terminal-state branches client-side after the fetch (Linear's children
 * connection has no top-level state filter).
 */

import type { Command, OptionValues } from "commander";
import {
	buildIssueTreeQuery,
	DEFAULT_TREE_DEPTH,
	type GetIssueTreeResponse,
	type IssueTreeNode,
	MAX_TREE_DEPTH,
} from "../../queries/issue-tree.js";
import { formatTree } from "../../utils/format-tree.js";
import { createIssuesService } from "../../utils/issues-service-bootstrap.js";
import { handleAsyncCommand, outputSuccess } from "../../utils/output.js";
import { getRootOpts } from "../../utils/root-opts.js";

interface TreeOptions {
	depth?: string;
	includeClosed?: boolean;
}

export function setupTreeCommand(issues: Command): void {
	issues
		.command("tree <issueId>")
		.description(
			"Render the parent-and-children tree of an issue (DEV-4480). " +
				"One GraphQL call. Depth defaults to 3 (max 5).",
		)
		.option(
			"--depth <n>",
			`Tree depth, integer in [1, ${MAX_TREE_DEPTH}] (default ${DEFAULT_TREE_DEPTH})`,
			String(DEFAULT_TREE_DEPTH),
		)
		.option(
			"--no-include-closed",
			"Prune branches whose state is Done or Canceled. By default tree " +
				"renders all states because the tree's value is structural.",
		)
		.addHelpText(
			"after",
			"\nExamples:" +
				"\n  el-linear issues tree DEV-100" +
				"\n  el-linear issues tree DEV-100 --depth 5 --format summary" +
				"\n  el-linear issues tree DEV-100 --no-include-closed",
		)
		.action(handleAsyncCommand(handleTreeCommand));
}

export async function handleTreeCommand(
	issueId: string,
	options: OptionValues,
	command: Command,
): Promise<void> {
	const rootOpts = getRootOpts(command);
	const { graphQLService, linearService } = await createIssuesService(rootOpts);

	const treeOptions = options as TreeOptions;
	const depth = parseDepth(treeOptions.depth);
	// commander turns `--no-include-closed` into `includeClosed: false`; the
	// default is true (see option declaration).
	const includeClosed = treeOptions.includeClosed !== false;

	const resolvedId = await linearService.resolveIssueId(issueId);
	const result = await graphQLService.rawRequest<GetIssueTreeResponse>(
		buildIssueTreeQuery(depth),
		{ id: resolvedId },
	);
	if (!result.issue) {
		throw new Error(`Issue "${issueId}" not found`);
	}

	const filtered = includeClosed
		? result.issue
		: pruneTerminalStates(result.issue);

	// `--format` is a *root-program* option (see main.ts), so commander
	// surfaces it via `command.parent.opts()` — NOT via the subcommand
	// action's local `options` parameter. Reading from `rootOpts` mirrors
	// the precedent in `read-shortcut.ts`'s `--field` handling.
	// (DEV-4480 cycle-1 blocker.)
	if (rootOpts.format === "summary") {
		process.stdout.write(`${formatTree(filtered)}\n`);
		return;
	}
	outputSuccess(filtered);
}

function parseDepth(raw: string | undefined): number {
	if (raw === undefined) {
		return DEFAULT_TREE_DEPTH;
	}
	const n = Number.parseInt(raw, 10);
	if (!Number.isInteger(n) || n < 1 || n > MAX_TREE_DEPTH) {
		throw new Error(
			`--depth must be an integer in [1, ${MAX_TREE_DEPTH}]; got "${raw}".`,
		);
	}
	return n;
}

/**
 * Walk the tree depth-first and drop any node whose `state.type` is
 * `completed` or `canceled`. Pure function — does not mutate the input.
 * A pruned child takes its entire subtree with it (consistent with how
 * `issues list --no-include-closed` excludes closed work entirely).
 *
 * Assumes Linear's parent → children graph stays single-parent (a tree,
 * not a DAG). If Linear ever ships multi-parent issues, this recursion
 * would re-emit nodes reachable via multiple paths — at that point add
 * a `Set<string>` of seen `id`s to the walk. Today the assumption is
 * safe. Bounded recursion: `MAX_TREE_DEPTH=5` caps the call stack at
 * ≤6 frames (root + 5 children levels). (Cycle-1 nit.)
 */
function pruneTerminalStates(root: IssueTreeNode): IssueTreeNode {
	const kids = root.children?.nodes ?? [];
	const surviving = kids
		.filter((c) => !isTerminalState(c))
		.map((c) => pruneTerminalStates(c));
	return {
		...root,
		children: { nodes: surviving },
	};
}

function isTerminalState(node: IssueTreeNode): boolean {
	const t = node.state?.type;
	return t === "completed" || t === "canceled";
}
